default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  database: <%= ENV.fetch('MYSQL_DATABASE') { "database" } %>
  host: <%= ENV.fetch('MYSQL_HOST') { "127.0.0.1" } %>
  port: <%= ENV.fetch('MYSQL_PORT') { 3306 } %>
  username: <%= ENV.fetch('MYSQL_USER') { "user" } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { "password" } %>

development:
  <<: *default